# Purpose: Creates the container for running the US8 software.
# Usage: podman build -t us8executor:latest -f Dockerfile.deb
FROM ubuntu:24.04
ADD us8-@PROJECT_VERSION@-Linux.deb .
RUN apt-get update &&\
    apt-get -y --no-install-recommends install ./us8-@PROJECT_VERSION@-Linux.deb &&\
    apt-get autoremove -y &&\
    apt-get clean &&\
    rm -r /var/lib/apt/lists/* us8-@PROJECT_VERSION@-Linux.deb

